name: theme_state
description: A Flutter application that can change its themes dynamically using Riverpod and Shared preferences.

publish_to: "none"

version: 0.1.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pedantic: ^1.9.2
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.4
  shared_preferences: ^0.5.12+4

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
