name: moor_app
description: Moor + Riverpod = Task application with the best state-management library and reactive persistence library

publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  pedantic: ^1.9.2
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.4.0+1
  path_provider: ^1.6.27
  path: ^1.7.0
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.4
  flutter_slidable: ^0.5.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator: ^3.4.1
  build_runner: ^1.11.1

flutter:
  uses-material-design: true
