name: currency_converter
description: Yet another currency converter. For my mobile application assignment.

publish_to: "none"

version: 0.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  pedantic: ^1.9.2
  flutter_dotenv: ^3.1.0
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.4
  http: ^0.12.2
  intl: ^0.16.1
  url_launcher: ^5.7.10
  flutter_speed_dial: ^2.1.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets: 
    - .env
    - assets/
